import sys

from PyQt5 import uic
from PyQt5.QtWidgets import QApplication, QMainWindow, QDialog

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(632, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(60, 20, 521, 321))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_fernet_encrypt = QtWidgets.QWidget()
        self.tab_fernet_encrypt.setAccessibleName("")
        self.tab_fernet_encrypt.setObjectName("tab_fernet_encrypt")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_fernet_encrypt)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 511, 211))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_fe = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_fe.setObjectName("label_fe")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_fe)
        self.textEdit = QtWidgets.QTextEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMaximumSize(QtCore.QSize(250, 50))
        self.textEdit.setObjectName("textEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textEdit)
        self.label_2_fe = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2_fe.setObjectName("label_2_fe")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2_fe)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.key_fe = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.key_fe.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.key_fe.setObjectName("key_fe")
        self.horizontalLayout_3.addWidget(self.key_fe)
        self.generate_fe = QtWidgets.QPushButton(self.formLayoutWidget)
        self.generate_fe.setObjectName("generate_fe")
        self.horizontalLayout_3.addWidget(self.generate_fe)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.encrypt_fe = QtWidgets.QPushButton(self.formLayoutWidget)
        self.encrypt_fe.setObjectName("encrypt_fe")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.encrypt_fe)
        self.label_3_fe = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3_fe.setObjectName("label_3_fe")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3_fe)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.result_fe = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.result_fe.setReadOnly(True)
        self.result_fe.setObjectName("result_fe")
        self.horizontalLayout_4.addWidget(self.result_fe)
        self.copy_fe = QtWidgets.QPushButton(self.formLayoutWidget)
        self.copy_fe.setObjectName("copy_fe")
        self.horizontalLayout_4.addWidget(self.copy_fe)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab_fernet_encrypt, "")
        self.tab_fernet_decrypt = QtWidgets.QWidget()
        self.tab_fernet_decrypt.setObjectName("tab_fernet_decrypt")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_fernet_decrypt)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 511, 211))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2_fd = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_2_fd.setObjectName("label_2_fd")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2_fd)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.key_fd = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.key_fd.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.key_fd.setObjectName("key_fd")
        self.horizontalLayout_5.addWidget(self.key_fd)
        self.generate_fd = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.generate_fd.setObjectName("generate_fd")
        self.horizontalLayout_5.addWidget(self.generate_fd)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.decrypt_fd = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.decrypt_fd.setObjectName("decrypt_fd")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.decrypt_fd)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.textEdit_2 = QtWidgets.QTextEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_2.sizePolicy().hasHeightForWidth())
        self.textEdit_2.setSizePolicy(sizePolicy)
        self.textEdit_2.setMaximumSize(QtCore.QSize(250, 50))
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout_6.addWidget(self.textEdit_2)
        self.copy_fd = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.copy_fd.setObjectName("copy_fd")
        self.horizontalLayout_6.addWidget(self.copy_fd)
        self.formLayout_2.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.label_3_fd = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_3_fd.setObjectName("label_3_fd")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3_fd)
        self.result_fd = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_fd.sizePolicy().hasHeightForWidth())
        self.result_fd.setSizePolicy(sizePolicy)
        self.result_fd.setMinimumSize(QtCore.QSize(250, 0))
        self.result_fd.setMaximumSize(QtCore.QSize(250, 16777215))
        self.result_fd.setObjectName("result_fd")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.result_fd)
        self.label_fd = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_fd.setObjectName("label_fd")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_fd)
        self.tabWidget.addTab(self.tab_fernet_decrypt, "")
        self.tab_sha = QtWidgets.QWidget()
        self.tab_sha.setObjectName("tab_sha")
        self.tabWidget.addTab(self.tab_sha, "")
        self.tab_md5 = QtWidgets.QWidget()
        self.tab_md5.setTabletTracking(False)
        self.tab_md5.setObjectName("tab_md5")
        self.tabWidget.addTab(self.tab_md5, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 632, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_fe.setText(_translate("MainWindow", "Text to encrypt:"))
        self.label_2_fe.setText(_translate("MainWindow", "Key:"))
        self.generate_fe.setText(_translate("MainWindow", "Generate"))
        self.encrypt_fe.setText(_translate("MainWindow", "Encrypt"))
        self.label_3_fe.setText(_translate("MainWindow", "Result:"))
        self.copy_fe.setText(_translate("MainWindow", "Copy"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_fernet_encrypt), _translate("MainWindow", "Fernet Encryption"))
        self.label_2_fd.setText(_translate("MainWindow", "Key:"))
        self.generate_fd.setText(_translate("MainWindow", "Generate"))
        self.decrypt_fd.setText(_translate("MainWindow", "Decrypt"))
        self.copy_fd.setText(_translate("MainWindow", "Copy"))
        self.label_3_fd.setText(_translate("MainWindow", "Encrypted text:"))
        self.label_fd.setText(_translate("MainWindow", "Decrypted text:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_fernet_decrypt), _translate("MainWindow", "Fernet Decryption"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sha), _translate("MainWindow", "SHAs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_md5), _translate("MainWindow", "MD5 Hashing"))


class MyWidget(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


def except_hook(cls, exception, traceback):
    sys.__excepthook__(cls, exception, traceback)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = MyWidget()
    ex.show()
    sys.excepthook = except_hook
    sys.exit(app.exec_())